### ISSUE TITLE
should there be an corresponding router to each viewControler to manage how to route to other viewControllers

### ISSUE THREAD

**Issue by bupojung** [tiagomartinho/Reminders#3]
I see there is only one router called AppRouter in the app. If it have an reminder detail viewcontroller, how do you implement in this architecture.

**Comment by tiagomartinho** [comment]
My idea was to compose routers. If that would be implemented it would be possible to have an Onboarding Router (when the user first installs the app), a AuthenticationRouter (for example to signup/login the user), etc.

What do you think?

**Comment by tiagomartinho** [comment]
I will close this issue due to low activity.

Thanks!
